<?php

namespace Nucleus\Dashboard;

use Symfony\Component\Validator\Validator;
use Symfony\Component\Validator\ConstraintViolationList;
use ReflectionClass;

class ModelDefinition
{
    const VALIDATE_WITH_VALIDATOR = 0;
    const VALIDATE_WITH_CALLBACK = 1;
    const VALIDATE_WITH_METHOD = 2;

    protected $className;

    protected $name;

    protected $fields = array();

    protected $actions = array();

    protected $loader;

    protected $validationMethod = 0;

    public static function create()
    {
        return new ModelDefinition();
    }

    public function setClassName($className)
    {
        $this->className = trim($className, '\\');
        return $this;
    }

    public function getClassName()
    {
        return $this->className;
    }

    public function isAutoGenerated()
    {
        return $this->className === null;
    }

    public function setName($name)
    {
        $this->name = $name;
        return $this;
    }

    public function getName()
    {
        return $this->name;
    }

    public function setFields(array $fields)
    {
        $this->fields = array();
        array_map(array($this, 'addField'), $fields);
        return $this;
    }

    public function addField(FieldDefinition $field)
    {
        $this->fields[] = $field;
        return $this;
    }

    public function getField($name)
    {
        foreach ($this->fields as $field) {
            if ($field->getName() === $name) {
                return $field;
            }
        }
        return false;
    }

    public function getIdentifierField()
    {
        foreach ($this->fields as $field) {
            if ($field->isIdentifier()) {
                return $field;
            }
        }
        return false;
    }

    public function getFields()
    {
        return $this->fields;
    }

    public function getListableFields()
    {
        return array_filter($this->fields, function($f) { return $f->isListable(); });
    }

    public function getEditableFields()
    {
        return array_filter($this->fields, function($f) { return $f->isEditable(); });
    }

    public function setActions(array $actions)
    {
        $this->actions = array();
        array_map(array($this, 'addAction'), $actions);
        return $this;
    }

    public function addAction(ActionDefinition $action)
    {
        $this->actions[] = $action;
        return $this;
    }

    public function getAction($name)
    {
        foreach ($this->actions as $action) {
            if ($action->getName() === $name) {
                return $action;
            }
        }
        return false;
    }
    
    public function getActions()
    {
        return $this->actions;
    }

    public function setLoader($callback = null)
    {
        $this->loader = $callback;
        return $this;
    }

    public function getLoader()
    {
        return $this->loader;
    }

    public function hasLoader()
    {
        return $this->loader !== null;
    }

    public function setValidationMethod($method)
    {
        $this->validationMethod = $method;
        return $this;
    }

    public function getValidationMethod()
    {
        return $this->validationMethod;
    }

    public function setValidator($validator)
    {
        $this->validator = $validator;
        return $this;
    }

    public function getValidator()
    {
        return $this->validator;
    }

    /**
     * Loads a model using the $data according to the ModelDefinition (eg: using the model loader)
     * 
     * @param array $data
     * @return object
     */
    public function loadObject($data)
    {
        if ($this->loader === null) {
            return $this->instanciateObject($data);
        }
        $loaderArgs = $data;
        if ($idField = $this->getIdentifierField()) {
            $loaderArgs = $data[$idField->getProperty()];
        }
        $obj = call_user_func($this->loader, $loaderArgs);
        $this->populateObject($obj, $data);
        return $obj;
    }

    /**
     * Creates a new object according to the ModelDefinition
     * 
     * @param array $data
     * @return object
     */
    public function instanciateObject($data = array())
    {
        if ($this->className !== null) {
            $class = new ReflectionClass($this->className);
            $obj = $class->newInstance();
        } else {
            $obj = new \stdClass();
        }
        $this->populateObject($obj, $data);
        return $obj;
    }

    /**
     * Populates an object with the specified data according to the given ModelDefinition
     * 
     * @param object $obj
     * @param array $data
     * @return object
     */
    public function populateObject($obj, $data)
    {
        foreach ($this->getEditableFields() as $f) {
            $p = $f->getProperty();
            if (!isset($data[$p])) {
                continue;
            }
            $f->setValue($obj, $data[$p]);
        }
        return $obj;
    }

    /**
     * Converts an object to an array representation according to the ModelDefinition
     * 
     * @param object $obj
     * @return array
     */
    public function convertObjectToArray($obj)
    {
        $array = array();
        $class = new ReflectionClass($obj);
        foreach ($this->getListableFields() as $f) {
            $array[$f->getProperty()] = $f->getValue($obj);
        }
        return $array;
    }

    /**
     * Validates an object using fields validators
     * 
     * @param object $object
     */
    public function validateObject($object)
    {
        if ($this->validationMethod === self::VALIDATE_WITH_METHOD) {
            if (!method_exists($object, 'validate')) {
                throw new DefinitionBuilderException("Missing validate() method on object");
            }
            if (!call_user_func(array($object, 'validate'))) {
                $violations = implode("\n", $object->getValidationFailures());
                throw new ValidationException($violations);
            }
            return true;
        }

        if ($this->validationMethod === self::VALIDATE_WITH_CALLBACK) {
            if ($this->validator === null) {
                throw new DefinitionBuilderException("Missing validation callback");
            }
            return call_user_func($this->validator, array($object, $this));
        }

        if ($this->validator === null) {
            return true;
        }

        if ($this->className !== null) {
            $violiations = $this->validator->validate($object);
        } else {
            $violiations = new ConstraintViolationList();
            foreach ($this->fields as $field) {
                $value = $field->getValue($object);
                $violiations->addAll($this->validator->validateValue($value, $field->getConstraints()));
            }
        }

        if (count($violiations)) {
            throw new ValidationException($violiations);
        }
        return true;
    }
}
